included:
  - Sources
disabled_rules:
  - type_name
  - nesting
  - line_length
  - force_try
  - force_cast
variable_name:
  excluded:
    - m
    - id

function_body_length:
  warning: 100
cyclomatic_complexity:
  warning: 30
